spring:
  datasource:
    url: jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=hotel_db;encrypt=true;trustServerCertificate=true;
    username: hotel_app
    password: Password123!
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    cache: false